//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_AUTO
    {
        public int DNI { get; set; }
        public string NOMBRE { get; set; }
        public string apellido { get; set; }
        public string CORREO { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string PLACA { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public string CLASE { get; set; }
        public Nullable<int> NUM_ASI { get; set; }
    }
}
